sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
  - docker login -u janellekim3 -p kaicurl37*

deploy:
  provider: script
  script: docker push mannydesigns/mode
  on:
    branch: master